# Owned by grafana-delivery-squad
name: Provide auto token from grafana-delivery-bot
run-name: generate-delivery-bot-auth-token
on:
  workflow_call:
    outputs:
      token:
        description: "grafana-delivery-bot token"
        value: ${{ jobs.generate_token.outputs.token }}

jobs:
  generate_token:
    runs-on: ubuntu-latest
    steps:
      - name: "Generate token"
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_ID }}
          private_key: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_PEM }}
