# Owned by grafana-delivery-squad
name: Sync to security mirror
run-name: sync-to-security-mirror-${{ github.ref_name }}-${{ github.head_ref }}
on:
  pull_request_target:
    types:
      - closed
    branches:
      - "main"
      - "v*"

jobs:
  trigger_downstream_security_mirror:
    if: github.event.pull_request.merged == true
    uses: grafana/security-patch-actions/.github/workflows/mirror-branch-and-apply-patches.yml@main
    with:
      ref: "${{ github.base_ref }}"
      src_repo: "${{ github.repository }}"
      dest_repo: "${{ github.repository }}-security-mirror"
      patch_repo: "${{ github.repository }}-security-patches"
    secrets: inherit
