# Owned by grafana-delivery-squad
# Intended to be dropped into the security-mirror repo, Ex: grafana/grafana-security-mirror
name: Sync to security mirror
run-name: sync-to-security-mirror
on:
  push:
    branches:
      - "main"

jobs:
  tester:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set file changes
        run: |
          echo "DIFF=$(git diff --name-only ${{ github.event.after }} ${{ github.event.before }})" >> $GITHUB_ENV
      - name: echo env var
        run:
          echo ${{ env.DIFF }}
      - name: Analyze file changes 
        run: |
          for file_change in ${{ env.DIFF }}; do
            echo $file_change
            echo $(dirname "$file_change") was changed

          done
  #   trigger_downstream_security_mirror:
  #     concurrency: security-mirror-${{ github.ref }}
  #     if: github.event.pull_request.merged == true
  #     uses: grafana/security-patch-actions/.github/workflows/mirror-branch.yml@main
  #     with:
  #       ref: "${{ github.base_ref }}" # this is the target branch name, Ex: "main"
  #       src_repo: "${{ github.repository }}"
  #       dest_repo: "${{ github.repository }}-security-mirror"
  #     secrets: inherit
  #   trigger_downstream_security_patching:
  #     concurrency: security-mirror-${{ github.ref }}
  #     needs: trigger_downstream_security_mirror
  #     if: github.event.pull_request.merged == true
  #     uses: grafana/security-patch-actions/.github/workflows/apply-patches.yml@main
  #     with:
  #       ref: "${{ github.base_ref }}"
  #       dest_repo: "${{ github.repository }}-security-mirror"
  #       patch_repo: "${{ github.repository }}-security-patches"
  #     secrets: inherit
