# Owned by grafana-delivery-squad
name: Check for security patch conflicts
run-name: check-security-patch-conflicts-${{ github.ref_name }}-${{ github.head_ref }}
on:
  pull_request_target:
    types:
      - opened
    branches:
      - "main"
      - "v*"

jobs:
  trigger_downstream_patch_check:
    uses: grafana/security-patch-actions/.github/workflows/test-patches.yml@main
    with:
      ref: "${{ github.base_ref }}"
      src_repo: "${{ github.repository }}"
      patch_repo: "${{ github.repository }}-security-patches"
    secrets: inherit
