# Owned by grafana-delivery-squad
# Intended to be dropped into the base repo Ex: grafana/grafana
name: Check for patch conflicts
run-name: check-patch-conflicts-${{ github.base_ref }}-${{ github.head_ref }}
on:
<<<<<<< HEAD
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
=======
  pull_request_target:
    types:
      - opened
>>>>>>> 148b6186b70fce90e9d3b830094bb97c70a2f40f
    branches:
      - "main"
      - "v*.*.*"
      - "release-*"

# Since this is run on a pull request, we want to apply the patches intended for the
# target branch onto the source branch, to verify compatibility before merging.
jobs:
  trigger_downstream_patch_check:
<<<<<<< HEAD
    uses: grafana/security-patch-actions/.github/workflows/test-patches.yml@develop
=======
    uses: grafana/security-patch-actions/.github/workflows/test-patches.yml@main
>>>>>>> 148b6186b70fce90e9d3b830094bb97c70a2f40f
    with:
      src_repo: "${{ github.repository }}"
      src_ref: "${{ github.head_ref }}" # this is the source branch name, Ex: "feature/newthing"
      patch_repo: "${{ github.repository }}-security-patches"
      patch_ref: "${{ github.base_ref }}" # this is the target branch name, Ex: "main"
    secrets: inherit
